# Лабораторная работа № 1. Введение в язык программирования Python. Домашнее задание.

## 1. Базовый уровень

### Задание 1.1

Напишите функцию *limited_sum(my_list, n)*, которая принимает список чисел *my_list* (количество товаров разных марок) и число *n* и возвращает сумму всех чисел списка меньше либо равных *n* (суммарное количество товаров, которых в наличие меньше либо равно *n*).

In [ ]:
def limited_sum(my_list, n):
    # напишите здесь ваше решение
    sum = 0
    for i in my_list:
      if i <= n:
        sum = sum + i

    return sum

In [ ]:
print(limited_sum([1, 2, 3, 4, 5, 6, 3, 7], 7) == 31)
print(limited_sum([1, 2, 3, 4, 4, 3, 2, 1], 7) == 20)
print(limited_sum([1, 2, 3, 4, 4, 3, 2, 1], 3) == 12)
print(limited_sum([1, 2, 3, 4, 5, 6, 3, 7], 5) == 18)
print(limited_sum([1, 2, 3, 4, 5, 6, 3, 7], 3) == 9)

True
True
True
True
True

### Задание 1.2

Напишите функцию *factorial(n)*, принимающую число *n* и рассчитывающую его факториал.

$n! = 1 \cdot 2 \cdot 3 \cdot \dots \cdot (n - 1) \cdot n$

In [ ]:
def factorial(n):
    # напишите здесь ваше решение
    factorial = 1
    for i in range(1,n+1,1):
      factorial = factorial*i
    return factorial

In [ ]:
print(factorial(3) == 6)
print(factorial(5) == 120)
print(factorial(9) == 362880)
print(factorial(13) == 6227020800)

True
True
True
True

### Задание 1.3

Пользователь делает вклад в размере *a* рублей сроком на *years* лет под *n* % годовых (каждый год размер его вклада увеличивается на *n* %. Эти деньги прибавляются к сумме вклада, и на них в следующем году тоже будут проценты). Написать функцию *bank(a, years, n)*, возвращающую сумму, которая будет на счету пользователя.

In [ ]:
def bank(a, years, n):
    # напишите здесь ваше решение
    sum = round(a*(1+(n/100))**years,1)

    return sum

In [ ]:
print(bank(1000, 0, 10) == 1000)
print(bank(1000, 1, 10) == 1100)
print(bank(1000, 2, 10) == 1210)
print(bank(1000, 3, 10) == 1331)
print(bank(1000, 4, 10) == 1464.1)

True
True
True
True
True

### Задание 1.4

Написать функцию *is_prime(num)*, принимающую 1 аргумент *num* — число от 0 до 1000, и возвращающую *True*, если оно простое, и *False* - иначе.

In [ ]:
def is_prime(num):
    # напишите здесь ваше решение
    if num == 1:
      print("Единица имеет только один делитель")
      return False
    else:
      n = 0
      for i in range (1,round(num/2) + 1,1):
        if (num%i == 0)&(i!=1)&(i!=num):
          return False

      return True

In [ ]:
print(is_prime(1) == False)
print(is_prime(2) == True)
print(is_prime(17) == True)
print(is_prime(63) == False)
print(is_prime(41) == True)

Единица имеет только один делитель
True
True
True
True
True

### Задание 1.5

Написать функцию *has_dup(my_list)*, которая принимает на вход список *my_list* и возвращает *True*, если список содержит дубликаты, и *False*, если дубликатов нет.

In [ ]:
def has_dup(my_list):
    # напишите здесь ваше решение
    res = 0
    for i in my_list:
      n = my_list.count(i)

      if n >= 2:
        return True
        break
    if n < 2:
      return False

In [ ]:
print(has_dup([1,2,3,4,5]) == False)
print(has_dup([1,2,3,3,5]) == True)
print(has_dup([1,2,3,4,'one','two','three','four']) == False)
print(has_dup([11,2,35,4,55,15,17,3,4,35,1]) == True)
print(has_dup([1,2,3,4,'one','two','three','four','one']) == True)

True
True
True
True
True

### Задание 1.6

На основании 3-х исходных множеств (передаются в качестве аргументов функции *diff(set1, set2, set3)*) требуется написать функцию, которая будет возвращать либо симметричную разность, либо просто разность (если дополнительный аргумент функции *symmetric* имеет значение *False*) приведенных объектов в порядке: 1-ое множество, 2-ое множество, 3-е множество.

In [ ]:
def diff(set1, set2, set3, symmetric = True):
    # напишите здесь ваше решение
  if symmetric:
    res = set1 ^ set2 ^ set3

  else:
    res = (set1 - set2) - set3

  return res

In [ ]:
set1 = {3, 4, 5, 6, 20}
set2 = {4, 6, 7, 8, 9}
set3 = {5, 3, 8, 1}

print(diff(set1, set2, set3) == {1, 20, 7, 9})
print(diff(set1, set2, set3, symmetric = False) == {20})

True
True

### Задание 1.7

Есть два списка чисел: *list1* - цены товаров в одном магазине - и *list2* - цены товаров в другом магазине. Напишите функцию *compare_prices(list1, list2)*, которая будет сравнивать средние цены (среднее берётся по всем товарам), минимальные и максимальные цены в магазинах. Если первое значение меньше, то надо вернуть 'First', если второе, то 'Second', а если равны, то 'Equal'.

In [ ]:
def compare_prices(list1, list2):
    # напишите здесь ваше решение
    res = []
    if (sum(list1)/len(list1)) <  (sum(list2)/len(list2)):
      res.append('First')
    elif (sum(list1)/len(list1)) == (sum(list2)/len(list2)):
      res.append('Equal')
    else:
      res.append('Second')

    if (min(list1)) <  (min(list2)):
      res.append('First')
    elif (min(list1)) == (min(list2)):
      res.append('Equal')
    else: res.append('Second')

    if (max(list1)) <  (max(list2)):
      res.append('First')
    elif (max(list1)) == (max(list2)):
      res.append('Equal')
    else: res.append('Second')

    return res

In [ ]:
print(compare_prices([1, 2, 3], [2, 2, 2]) == ['Equal', 'First', 'Second'])
print(compare_prices([2, 2, 1], [4]) == ['First', 'First', 'First'])
print(compare_prices([3, 5], [2, 4, 6]) == ['Equal', 'Second', 'First'])
print(compare_prices([1, 7], [2, 4, 7]) == ['First', 'First', 'Equal'])

True
True
True
True

## 2. Продвинутый уровень

### Задание 2.1

Имеется список пар (фамилия, долг) *my_list* и число *dept*. Нужно написать функцию *sorted_dept(my_list, dept)*, которая для каждой фамилии находит суммарный долг, сортирует фамилии в порядке уменьшения суммарного долга и выводит отсортированный список фамилий, у которых долг строго больше *dept*. Одна и та же фамилия может встречаться несколько раз, и тогда долги по ней суммируются.

In [ ]:
def sorted_dept(my_list, dept):
    # напишите здесь ваше решение
    # создаем словарь, проходимся по списку, который нам дан и проверяем есть ли в нашем словаре данный ключь(фамилия),
    # если есть увеличиваем значение по этому ключу, если такого ключа нет, то добавляем ключ со значением 1

    # выводит фамилии отсортированные по количеству долгов (убывание)
    dict_fam_debt = dict()
    keys_dict_fam_debt = my_list.keys()
    sum_dept = 0
    for fam, dolg in my_list:
      sum_dept =
      if (dict_fam_debt.)
      dict_fam_debt.setdefault()

    return

In [ ]:
print(sorted_dept([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 1) == ['Sidorov', 'Ivanov', 'Petrov'])
print(sorted_dept([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 2) == ['Sidorov', 'Ivanov'])
print(sorted_dept([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 3) == ['Sidorov'])
print(sorted_dept([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Sidorov', 4)], 4) == [])
print(sorted_dept([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Petrov', 4)], 2) == ['Petrov', 'Ivanov'])
print(sorted_dept([('Ivanov', 1), ('Petrov', 2), ('Ivanov', 2), ('Petrov', 4)], 3) == ['Petrov'])

{'Ivanov': 3, 'Petrov': 2, 'Sidorov': 4}
False
{'Ivanov': 3, 'Petrov': 2, 'Sidorov': 4}
False
{'Ivanov': 3, 'Petrov': 2, 'Sidorov': 4}
False
{'Ivanov': 3, 'Petrov': 2, 'Sidorov': 4}
False
{'Ivanov': 3, 'Petrov': 6}
False
{'Ivanov': 3, 'Petrov': 6}
False

### Задание 2.2

На входе имеем список строк разной длины. Необходимо написать функцию *all_eq(my_list)*, которая вернет новый список из строк одинаковой длины. Длину итоговой строки определяем исходя из самой большой из них. Если конкретная строка короче самой длинной, дополнить ее нижними подчеркиваниями с правого края до требуемого количества символов. Расположение элементов начального списка не менять.

In [ ]:
def all_eq(my_list):
    # напишите здесь ваше решение
    return

In [ ]:
print(all_eq(['крот', 'белка', 'выхухоль']) == ['крот____', 'белка___', 'выхухоль'])
print(all_eq(['a', 'aa', 'aaa', 'aaaa', 'aaaaa']) == ['a____', 'aa___', 'aaa__', 'aaaa_', 'aaaaa'])
print(all_eq(['qweasdqweas', 'q', 'rteww', 'ewqqqqq']) == ['qweasdqweas', 'q__________', 'rteww______', 'ewqqqqq____'])

### Задание 2.3

Предоставлен список натуральных чисел. Требуется сформировать из них множество. Если какое-либо число повторяется, то преобразовать его в строку по образцу: например, если число 4 повторяется 3 раза, то в множестве будет следующая запись: само число 4, строка «44» (второе повторение, т.е. число дублируется в строке), строка «444» (третье повторение, т.е. строка множится на 3). Реализуйте вывод множества через функцию *set_gen(my_list)*.

In [ ]:
def set_gen(my_list):
    # напишите здесь ваше решение
    return

In [ ]:
print(set_gen([1, 1, 3, 3, 1]) == {1, 3, '111', '33', '11'})
print(set_gen([5, 5, 5, 5, 5, 5, 5]) == {'5555555', 5, '55', '55555', '5555', '555555', '555'})
print(set_gen([2, 2, 1, 2, 2, 5, 6, 7, 1, 3, 2, 2]) == {1, 2, 3, 5, 6, 7, '22', '2222', '22222', '222', '11', '222222'})

### Задание 2.4

Дана строка в виде случайной последовательности чисел от 0 до 9. Требуется создать словарь, который в качестве ключей будет принимать данные числа (т. е. ключи будут типом *int*), а в качестве значений – количество этих чисел в имеющейся последовательности. Для построения словаря создайте функцию *count_it(sequence)*, принимающую строку из цифр. Функция должна возвратить словарь из 3-х самых часто встречаемых чисел.

In [ ]:
def count_it(sequence):
    # напишите здесь ваше решение
    return

In [ ]:
print(count_it('1111111111222') == {1: 10, 2: 3})
print(count_it('123456789012133288776655353535353441111') == {3: 8, 1: 7, 5: 7})
print(count_it('007767757744331166554444') == {5: 3, 7: 6, 4: 6})

### Задание 2.5

Вам известны количество продаж разных товаров. Они представлены в виде списка *my_list*: первое значение - число продаж первого товара, второе значение - второго, и так далее. Напишите функцию *get_most_popular(my_list, n, threshold)*, которая будет выдавать список из порядковых номеров самых популярных товаров (порядковые номера - 0, 1, 2 и т.д.), чей объём продаж **выше** заданного числа *threshold*. Длина такого списка должна быть **не более** *n*, т.е. нужно выдать номера *n* самых популярных товаров.

In [ ]:
def get_most_popular(my_list, n, threshold):
    # напишите здесь ваше решение
    return

In [ ]:
print(get_most_popular([1, 2, 3, 4, 5, 6, 3, 7], 7, 1) == [7, 5, 4, 3, 2, 6, 1])
print(get_most_popular([1, 2, 3, 4, 5, 6, 3, 7], 7, 2) == [7, 5, 4, 3, 2, 6, 1])
print(get_most_popular([1, 2, 3, 4, 5, 6, 3, 7], 3, 2) == [7, 5, 4])
print(get_most_popular([1, 2, 3, 4, 5, 6, 3, 7], 3, 5) == [7, 5, 4])
print(get_most_popular([1, 2, 3, 4, 5, 6, 3, 7], 5, 5) == [7, 5, 4])